backend/models/Movimientos.php
<?php

namespace backend\models;

use yii\helpers\ArrayHelper;
use Yii;
use backend\models\ProductoServicios;
use backend\models\TipoMovimientos;
use backend\models\DetalleMovimientos;
/**
 * This is the model class for table "tbl_movimientos".
 *
 * @property integer $idMovimiento
 * @property string $documentoRef
 * @property string $observaciones
 * @property integer $codProdServicio
 * @property integer $cantidad
 * @property string $estado
 */
class Movimientos extends \yii\db\ActiveRecord
{

     public $password;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_movimientos';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fecha','codigoTipo','documentoRef', 'observaciones','estado'/*, 'codProdServicio', 'cantidad', */], 'required'],
            // [['codProdServicio', 'cantidad'], 'integer'],
            [['documentoRef','observaciones'], 'string', 'max' => 1000],
            [['estado'], 'string', 'max' => 10]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'idMovimiento' => 'No. Mov',
            'codigoTipo' => 'Tipo',
            'documentoRef' => 'Doc. Referencia',
             'observaciones' => 'Observaciones',
            'codProdServicio' => 'Producto',
            'cantidad' => 'Cantidad',
            'estado' => 'Estado',
            'fecha' => 'Fecha',

        ];
    }

    public function getIdMovimiento()
    {
        return $this->hasMany(DetalleMovimientos::className(), ['idMovimiento' => 'idMovimiento']);
    }

    public function getcodProdServicio0()
    {
        return $this->hasOne(ProductoServicios::className(), ['codProdServicio' => 'codProdServicio']);
    }

    public function getcodigoTipo0()
    {
        return $this->hasOne(TipoMovimientos::className(), ['codigoTipo' => 'codigoTipo']);
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
          return $this->fecha = date('Y-m-d', strtotime( $this->fecha));
         
        } else {
            return  $this->fecha = '0000-00-00'; 
             
        }
    }

    public function afterFind()
      {
      $this->fecha = date('d-m-Y', strtotime( $this->fecha));
       parent::afterFind();
      }

      public function getCantidadProductos()
      {
        
      }


    //   public function init()
    // {
    //     parent::init();

    //     $this->codProdServicio = [
    //         [
               
    //             'codProdServicio' => ArrayHelper::map(ProductoServicios::find()->andwhere(['=','tipo','Producto'])->asArray()->all(), 'codProdServicio', 'codProdServicio'),

    //             'cantidad'  => 1
    //         ],
    //     ];
    // }
}

backend/controllers/MovimientosController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\TipoMovimientos;
use backend\models\Movimientos;
use backend\models\DetalleMovimientos;
use backend\models\MovimientosSesion;
use backend\models\MovimientosSesionUpdate;
use backend\models\search\MovimientosSearch;
use backend\models\ProductoCatalogo;
use backend\models\ProductoProveedores;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use backend\models\ProductoServicios;
use backend\models\Funcionario;
use yii\helpers\Html;
use backend\models\Empresa;
use yii\filters\AccessControl;

/**
 * MovimientosController implements the CRUD actions for Movimientos model.
 */
class MovimientosController extends BaseController
{
  public function behaviors()
  {
      return [
          'access' => [
            'class' => AccessControl::className(),
            'rules' => [
              [
                'actions' => ['index','view','create','update','delete',
                'tipo','delete-tipo', 'tipou', 'delete-tipou', 'referencia',
                'delete-referencia', 'referenciau', 'delete-referenciau', 'observaciones',
                'delete-observaciones', 'observacionesu', 'delete-observacionesu', 'cantidad',
                'estado', 'delete-estado', 'delete-estadou', 'additemi', 'additemu',
                'borrar-todo', 'borrar-todou', 'deleteall', 'deleteallu', 'aplicarmovimiento',
                'complete', 'deleteitem', 'deleteitemu', 'report', 'busqueda_producto'],
                'allow' => true,
                'roles' => ['@'],
              ]
            ],
          ],
          'verbs' => [
              'class' => VerbFilter::className(),
              'actions' => [
                  'delete' => ['post'],
              ],
          ],
      ];
  }

    /**
     * Lists all Movimientos models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MovimientosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Movimientos model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Movimientos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    // public function actionCreate()
    // {
    //     $model = new Movimientos();

    //     if ($model->load(Yii::$app->request->post()) && $model->save()) {
    //         Yii::$app->getSession()->setFlash('success', '<span class="glyphicon glyphicon-ok-sign"></span> <strong>Éxito!</strong><br><br>El movimiento a inventario ha sido realizado correctamente.');
    //         return $this->redirect(['create', 'model' => $model]);
    //     } else {
    //         return $this->render('create', [
    //             'model' => $model,
    //         ]);
    //     }
    // }
    public function actionCreate()
     {
         return $this->render('create');
     }
    /**
     * Updates an existing Movimientos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    // public function actionUpdate($id)
    // {
    //     $model = $this->findModel($id);

    //     if ($model->load(Yii::$app->request->post()) && $model->save()) {
    //         Yii::$app->getSession()->setFlash('success', '<span class="glyphicon glyphicon-ok-sign"></span> <strong>Éxito!</strong><br><br>El movimiento a inventario ha sido aplicado correctamente.');
    //         return $this->redirect(['create', 'model' => $model]);
    //     } else {
    //         return $this->render('update', [
    //             'model' => $model,
    //         ]);
    //     }
    // }


    //función para la vista de actualizar

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        //Definimos c como null para comprobación
                $c=null;
                //Baseamos el contenido que puede quedar de otro detalle
                MovimientosSesionUpdate::setContenidoMovimiento(null);
                //Abrimos el contenido
                $compra = MovimientosSesionUpdate::getContenidoMovimiento(); /////

                //Me obtiene los datos del detalle del encabezado correspondiente
                $query = new yii\db\Query();
                $data = $query->select(['codProdServicio','cantidad','cantidadinv','cantidadinvant'/*,'observaciones','estado'*/])
                    ->from('tbl_detalle_movimientos')
                    ->where(['=','idMovimiento', $model->idMovimiento])
                    ->distinct()
                    ->all();
                //Recorre dos datos para cargar las variables de la tabla correspondiente a ese encabezado prefactura
                foreach($data as $row){
                    $codProdServicio = $row['codProdServicio'];
                    $cantidad = $row['cantidad'];
                    $cantidadinv = $row['cantidadinv'];
                    $cantidadinvant = $row['cantidadinvant'];//
                    // $observaciones = $row['observaciones'];
                    // $estado = $row['estado'];
                   if ($codProdServicio!='') {
                        //Si no existe producto repetido, se asigna lo mandado por POST
                        if($c==null)
                        {   //cargo las variables de la tabla
                            $modelProd = ProductoServicios::find()->where(['codProdServicio'=>$codProdServicio])->one();

                            $_POST['cod']= $codProdServicio;
                            $_POST['cant']= $cantidad;
                            $_POST['can_ant']=  $cantidadinvant;
                            $_POST['cantinv']= $cantidadinv;
                            $_POST['desc']= $modelProd ? $modelProd->nombreProductoServicio : 'Este producto ya no existe en invetario';
                            $_POST['prec']= $modelProd ? $modelProd->precioVentaImpuesto : 0;
                            // $_POST['obs']= $observaciones;
                            // $_POST['est']= $estado;

                            $compra[] = $_POST;
                            //echo $model->nombreProductoServicio;
                        }
                        //Guardamos el contenido
                        MovimientosSesionUpdate::setContenidoMovimiento($compra);
                    }
                }

            return $this->render('update', [
                'model' => $model,
            ]);
    }



    /**
     * Deletes an existing Movimientos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Movimientos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Movimientos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Movimientos::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
     //Esta funcion me amacena los datos del tipo en session movimientos
            public function actionTipo(){
                if(Yii::$app->request->isAjax){
                    $idTipo = Yii::$app->request->post('idTipo');
                    MovimientosSesion::setTipo((int)$idTipo);
                    Yii::$app->response->redirect(array('movimientos/create'));
                }
            }

    //Esta funcion me elimina los datos del Tipo almacenados en session movimientos
            public function actionDeleteTipo()
            {
                MovimientosSesion::setTipo(null);//Para borrar Tipo
                Yii::$app->response->redirect(array('movimientos/create'));
            }
//Esta funcion me amacena los datos del tipo en session movimientos update
            public function actionTipou(){
                if(Yii::$app->request->isAjax){
                    $idTipo = Yii::$app->request->post('idTipo');
                    MovimientosSesionUpdate::setTipo((int)$idTipo);

                    $idMo = MovimientosSesionUpdate::getId_movimiento();
                    Yii::$app->response->redirect(array( 'movimientos/update', 'id' => $idMo ));
                    // Yii::$app->response->redirect(array('movimientos/create'));
                }
            }
    //Esta funcion me elimina los datos del Tipo almacenados en session movimientos update
            public function actionDeleteTipou()
            {
                MovimientosSesionUpdate::setTipo(null);//Para borrar Tipo
                 $idMo = MovimientosSesionUpdate::getId_movimiento();
                Yii::$app->response->redirect(array( 'movimientos/update', 'id' => $idMo ));
                // Yii::$app->response->redirect(array('movimientos/create'));
            }

     //Esta funcion me agrega nuevas referencias  para session de movimientos
            public function actionReferencia(){
                if (Yii::$app->request->post('new-referencia')) {
                    $idReferencia = Yii::$app->request->post('new-referencia');
                    MovimientosSesion::setReferencia($idReferencia);
                    Yii::$app->response->redirect(array('movimientos/create'));
                }else {

backend/views/movimientos/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\MovimientosSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="movimientos-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'idMovimiento') ?>

    <?= $form->field($model, 'documentoRef') ?>

    <?= $form->field($model, 'observaciones') ?>

    <?= $form->field($model, 'codProdServicio') ?>

    <?= $form->field($model, 'cantidad') ?>

    <?php // echo $form->field($model, 'estado') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/movimientos/busca_productos.php
<!-- Modal -->
			<div class="modal fade bs-example-modal-lg" id="modalinventario" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			  <div class="modal-dialog modal-lg" role="document">
				<div class="modal-content">
				  <div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel">Buscar productos</h4>
				  </div>
				  <div class="modal-body">
					<form class="form-horizontal">
					  <div class="form-group">
						<div class="col-sm-6">
						  <input type="text" class="form-control" id="q" placeholder="Buscar productos" onkeyup="load(1)">
						</div>
						<button type="button" class="btn btn-default" onclick="load(1)"><span class='glyphicon glyphicon-search'></span> Buscar</button>
					  </div>
					</form>
					<div id="loader" style="position: absolute;	text-align: center;	top: 55px;	width: 100%;display:none;"></div><!-- Carga gif animado -->
					<div class="outer_div" ></div><!-- Datos ajax Final -->
				  </div>
				  <div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
					
				  </div>
				</div>
			  </div>
			</div>

backend/views/movimientos/create.php
<?php

use yii\helpers\Html;
use kartik\widgets\AlertBlock;
use backend\models\MovimientosSesion;
use yii\bootstrap\Modal;
$load_buton = \Yii::$app->request->BaseUrl.'/img/load_buton.gif';
/* @var $this yii\web\View */
/* @var $model backend\models\Movimientos */

$this->title = 'Crear Movimientos';
$this->params['breadcrumbs'][] = ['label' => 'Movimientos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $tipo = MovimientosSesion::getTipo(); ?>
<?php $referencia = MovimientosSesion::getReferencia(); ?>
<?php $producto = MovimientosSesion::getContenidoMovimiento(); ?>
<?php $observaciones = MovimientosSesion::getObservaciones(); ?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script type="text/javascript">
window.onkeydown = tecla;

	function tecla(event) {
		//event.preventDefault();
		num = event.keyCode;

		if(num==113)
			$('#modalinventario').modal('show');//muestro la modal

	}

    $(document).ready(function(){
       // $('[data-toggle="modal"]').tooltip();
        $('[data-toggle="modal"]').popover();
        $('#tabla_lista_productos').DataTable();
    });

  function load(page){
        var parametros = {"action":"ajax","page":page};
        $("#loader").fadeIn('slow');
        $.ajax({
            url:'paises_ajax.php',
            data: parametros,
             beforeSend: function(objeto){
            $("#loader").html("<img src='loader.gif'>");
            },
            success:function(data){
                $(".outer_div").html(data).fadeIn('slow');
                $("#loader").html("");
            }
        })
    }

  function obtenerTipo(){

    var idTipo = document.getElementById("ddl-codigoTipo").value;
    $.ajax({
        url:"<?php echo Yii::$app->getUrlManager()->createUrl('movimientos/tipo') ?>",
        type:"post",
        data: {'idTipo': idTipo},
    }) ;
}

//Transformar a mayúsculas todos los caracteres
function Mayuculas(tx){
	//Retornar valor convertido a mayusculas
	return tx.toUpperCase();
}

  function obtenerObservaciones(){

    var observaciones = document.getElementById("observaciones").value;
    $.ajax({
        url:"<?php echo Yii::$app->getUrlManager()->createUrl('movimientos/observaciones') ?>",
        type:"post",
        data: {'observaciones': observaciones},
    }) ;
}

  function obtenerEstado(){

    var estado = document.getElementById("estado").value;
    $.ajax({
        url:"<?php echo Yii::$app->getUrlManager()->createUrl('movimientos/estado') ?>",
        type:"post",
        data: {'estado': estado},
    }) ;
}

  function obtenerReferencia(){

    var referencia = document.getElementById("referencia").value;
    $.ajax({
        url:"<?php echo Yii::$app->getUrlManager()->createUrl('movimientos/referencia') ?>",
        type:"post",
        data: {'referencia': referencia},
    }) ;
}
//activo el id redultadoBusqueda pendiente de una nueva busqueda
    $(document).ready(function() {
        $("#resultadoBusqueda").html('<p>ESPERANDO BUSQUEDA</p>');
    });
//me permite buscar por like los productos a BD
    function buscar() {
			var textoBusqueda_cod = $("input#busqueda_cod").val();
			var textoBusqueda_des = $("input#busqueda_des").val();
			var textoBusqueda_fam = $("input#busqueda_fam").val();
			var textoBusqueda_cat = $("input#busqueda_cat").val();
			var textoBusqueda_cpr = $("input#busqueda_cpr").val();
			var textoBusqueda_ubi = $("input#busqueda_ubi").val();
			if (textoBusqueda_cod == "" && textoBusqueda_des == "" && textoBusqueda_fam == "" && textoBusqueda_cat == "" && textoBusqueda_cpr == "" && textoBusqueda_ubi == "") {
					$("#resultadoBusqueda").html('<p>ESPERANDO BUSQUEDA</p>');

			} else {
            $.ajax({
                url:"<?php echo Yii::$app->getUrlManager()->createUrl('movimientos/busqueda_producto') ?>",
                type:"post",
								data: {
                    'valorBusqueda_cod' : textoBusqueda_cod,
                    'valorBusqueda_des' : textoBusqueda_des,
										'valorBusqueda_fam' : textoBusqueda_fam,
                    'valorBusqueda_cat' : textoBusqueda_cat,
                    'valorBusqueda_cpr' : textoBusqueda_cpr,
                    'valorBusqueda_ubi' : textoBusqueda_ubi },
                beforeSend : function() {
                  $("#resultadoBusqueda").html('<center><img src="<?= $load_buton; ?>" style="height: 32px;"></center>');
                },
								success: function(data){
                    $("#resultadoBusqueda").html(data);
                },
                error: function(msg, status,err){
                 //alert('No pasa 286');
                }
            });
        }
    }

function agrega_productoi(producto){
    //var producto = document.getElementById("producto").value;
    var observaciones = $("#observaciones").val();
    var estado = $("#estadoi").val();
    var cantidad = $("#cantidad").val();

    $.ajax({
        url:"<?php echo Yii::$app->getUrlManager()->createUrl('movimientos/additemi') ?>",
        type:"post",
        data: { 'estado': estado, 'observaciones' : observaciones, 'producto' : producto, 'cantidad': cantidad },
        success: function(){
					 $('#modalinventario').modal('hide');
           $("#conten_prom").load(location.href+' #conten_prom',''); //refrescar el div
           $("#conten_tipo").load(location.href+' #conten_tipo',''); //refrescar el div
           $("#conten_boton").load(location.href+' #conten_boton',''); //refrescar el div


            var $form = $('#formid');
            $form.find('input, textarea').val('');
             $form.find(':selected').val();

        },
        error: function(msg, status,err){
         // alert('Error');
        }
    });

}


function limpiar(){
         $("#observaciones").val("");
         $("#cantidad").val("");
         $("#estadoi").select2("val", "");
         $("#producto").select2("val", "");


}

function valida(e){
    tecla = (document.all) ? e.keyCode : e.which;

    //Tecla de retroceso para borrar, siempre la permite
    if (tecla==8){
        return true;
    }

    // Patron de entrada, en este caso solo acepta numeros
    patron =/[0-9]/;
    tecla_final = String.fromCharCode(tecla);
    return patron.test(tecla_final);
}

function alfanumerico(e){
    tecla = (document.all) ? e.keyCode : e.which;

    //Tecla de retroceso para borrar, siempre la permite
    if (tecla==8){
        return true;
    }

    // Patron de entrada, en este caso solo acepta numeros
    // patron =/[A-Za-z\s]/;
    patron =/[0-9]/;
    tecla_final = String.fromCharCode(tecla);
    return patron.test(tecla_final);
}

 function isNumberOrLetter(evt) {
           var charCode = (evt.which) ? evt.which : event.keyCode;
           if ((charCode > 65 && charCode < 91) || (charCode > 97 && charCode < 123) || (charCode > 47 && charCode < 58))
               return true;
           return false;
           }

 	//espacio que solo permite numero y decimal (.)
 	function isNumberDe(evt) {
 	    var nav4 = window.Event ? true : false;
 	    var key = nav4 ? evt.which : evt.keyCode;
 	    return (key <= 13 || key==46 || (key >= 48 && key <= 57));
 	}
</script>
<style>
    #modalinventario .modal-dialog{
    width: 74%!important;
    /*margin: 0 auto;*/
    }
</style>
<div class="movimientos-create">

    <?= AlertBlock::widget([
            'type' => AlertBlock::TYPE_GROWL,
            'useSessionFlash' => true
        ]);?>

    <h3><?= Html::encode($this->title) ?></h3>
    <br>
    <div id="conten_boton">  <p>
        <?= Html::a('Regresar', ['index'], ['class' => 'btn btn-default']) ?>

            <?= Html::a('Borrar', ['deleteall'], [
                        'class' => 'btn btn-danger',
                        'data' => [
                            'confirm' => '¿Seguro que quieres desechar los datos de este movimiento?',
                            'method' => 'post', ],]) ?>


        <?php if($tipo && $referencia && $observaciones && $producto) : ?>
            <?= Html::a('Guardar', ['complete'], ['class' => 'btn btn-success']) ?>
        <?php endif ?>
    </p>
</div>
    <?= $this->render('_form', [
        // 'model' => $model,
    ]) ?>

</div>
<?php
//echo $this->render('busca_productos', []);
//-----------------------modal para mostrar productos y agregarlos
        Modal::begin([
            'id' => 'modalinventario',
            'size'=>'modal-lg',
            'header' => '<center><h4 class="modal-title">Inventario de productos</h4></center>',
            'footer' => '<a href="#" class="btn btn-primary" data-dismiss="modal">Salir</a>',
        ]);
        //http://blog.collectivecloudperu.com/buscar-en-tiempo-real-con-jquery-y-bootstrap/
        echo '<div class="well"><div class="col-lg-2">
                                  '.Html::input('text', '', '', [/*'autofocus' => 'autofocus',*/ 'size' => '80', 'id' => 'busqueda_cod', 'class' => 'form-control', 'placeholder' =>'CÓDIGO LOCAL', 'onchange' => 'javascript:buscar()']).'
                                </div>
                                <div class="col-lg-2">
                                  '.Html::input('text', '', '', [/*'autofocus' => 'autofocus',*/ 'size' => '80', 'id' => 'busqueda_des', 'class' => 'form-control', 'placeholder' =>'DESCRIPCIÓN', 'onchange' => 'javascript:buscar()']).'
                                </div>
																<div class="col-lg-2">
                                  '.Html::input('text', '', '', [/*'autofocus' => 'autofocus',*/ 'size' => '80', 'id' => 'busqueda_fam', 'class' => 'form-control', 'placeholder' =>'CATEGORÍA', 'onchange' => 'javascript:buscar()']).'
                                </div>
                                <div class="col-lg-2">
                                  '.Html::input('text', '', '', [/*'autofocus' => 'autofocus',*/ 'size' => '80', 'id' => 'busqueda_cat', 'class' => 'form-control', 'placeholder' =>'CÓDIGO ALTERNO', 'onchange' => 'javascript:buscar()']).'
                                </div>
                                <div class="col-lg-2">
                                  '.Html::input('text', '', '', [/*'autofocus' => 'autofocus',*/ 'size' => '80', 'id' => 'busqueda_cpr', 'class' => 'form-control', 'placeholder' =>'CODIGO PROVEEDOR', 'onchange' => 'javascript:buscar()']).'
                                </div>
                                <div class="col-lg-2">
                                  '.Html::input('text', '', '', [/*'autofocus' => 'autofocus',*/ 'size' => '80', 'id' => 'busqueda_ubi', 'class' => 'form-control', 'placeholder' =>'UBICACIÓN', 'onchange' => 'javascript:buscar()']).'&nbsp;
                                </div>

                <table class="table table-hover" id="tabla_lista_productos">';
          echo '<thead>';
					printf('<tr><th width="150">%s</th>
											<th width="380">%s</th>
											<th width="100">%s</th>
											<th width="130">%s</th>
											<th width="120">%s</th>
											<th width="50">%s</th>
											<th width="140">%s</th>
											<th class="actions button-column" width="60">&nbsp;</th>
									</tr>',
													'CÓDIGO LOCAL',
													'DESCRIPCIÓN',
													'CANT.INV',
													'COD.ALTER',
													'CÓD.PROV',
													'UBICACIÓN',
													'PRECIO + IV'
													);
          echo '</thead>';
          echo '</table>

                <div id="resultadoBusqueda" style="height: 400px;width: 100%; overflow-y: auto; ">
                </div>

              </div>';

        Modal::end();

backend/views/movimientos/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use backend\models\ProductoServicios;
use backend\models\TipoMovimientos;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\MovimientosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Movimientos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="movimientos-index">

    <h3><?= Html::encode($this->title) ?></h3>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

   <p style="text-align:right">
        <?= Html::a('+ Nuevo Movimiento', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
 <div align="right">
            <label>Registro por pantalla: </label>
            <?php echo \nterms\pagesize\PageSize::widget(); ?>
        </div>
<?php  $dataProvider->pagination->defaultPageSize = 10; ?>
<!--?php  $dataProvider->pagination->pageSize = 10; ?-->
<div class="table-responsive">
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,'filterSelector' => 'select[name="per-page"]',
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

             [
                'attribute' => 'idMovimiento',
                'options'=>['style'=>'width:90px'],
            ],
            [
                'attribute' => 'codigoTipo',
                'label' => 'Cod',
                'options'=>['style'=>'width:60px'],
            ],
            [
            'attribute' =>'codigoTipo',
             'value' => 'codigoTipo0.descripcion',
            ],
            [
                'attribute' => 'documentoRef',
                'options'=>['style'=>'width:100px'],
            ],
            [
                'attribute' => 'observaciones',
                'options'=>['style'=>'width:35%'],
            ],
            // 'observaciones',
            // [
            // 'attribute' =>'codProdServicio',
            //  'value' => 'codProdServicio0.nombreProductoServicio',
            // ],
            // [
            //     'attribute' => 'cantidad',
            //     'options'=>['style'=>'width:90px'],
            // ],
             [
                'attribute' => 'estado',
                'options'=>['style'=>'width:90px'],
            ],
            [
                'attribute' => 'fecha',
                'options'=>['style'=>'width:90px'],
            ],
                        [
                'attribute' => 'usuario',
                'options'=>['style'=>'width:90px'],
            ],
            ['class' => 'yii\grid\ActionColumn',
            'template' => '{update}',
            'options'=>['style'=>'width:30px'],],
        ],
    ]); ?>
</div>
</div>